version: '3.5'

services:
  app-python:
    build: .
    container_name: app-flask
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      - mysql
    networks:
      - localnet
    env_file:
      - .env

  mysql:
    image: mysql:latest
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: 'sheva1111'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - localnet

volumes:
  mysql_data:
networks:
  localnet:
    name: localnet
    driver: bridge
